# ============================================================================
# Config file for merging flowcells
# ==========================================[ Sections for the users ]========
#
# samples from the different flowcells must follow a 1-to-t mapping
# ============================================================================
input_pattern: '*.fastq.gz'


##############################################################################
# Your section
#
# :Parameters:
#
# - options: string with any valid FastQC options
flowcell_paths:
    - todo


