all:
	echo "type *make clean* to delete temporary files"
clean: clean_files clean_directories
clean_files:
	rm -f config.yaml multiqc_config.yaml cluster_config.json slurm*out stats.txt schema.yaml merge_flowcells.rules  slurm*out merge_flowcells.rules config.yaml stats.txt  Makefile
clean_directories:
	rm -rf .snakemake
